# Generated by Django 4.2.28 on 2026-02-20 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя пользователя может содержать только латинские буквы и цифры.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
